FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm i -g serve

COPY . .

# When we reach production uncomment 

#RUN npm run build 

EXPOSE 3000

CMD ["npm", "run", "dev"]

#CMD [ "serve", "-s", "dist" ]